# Generated by Django 6.0.3 on 2026-05-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='medicine_type',
            field=models.CharField(choices=[('prescription', 'Thuốc kê đơn'), ('non_prescription', 'Thuốc không kê đơn')], default='non_prescription', max_length=30, verbose_name='Loại thuốc'),
        ),
    ]
